version: '3'

services:

    webserver:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            # - "./etc/ssl:/etc/ssl"
            - "./:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        networks:
            - hello
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
        # depends_on:
        #     - php
        #     - mysqldb

    phpfpmserver:
        image: shadow/php-fpm
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
        networks:
            - hello
        volumes:
            - "./etc/php-fpm-lib/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini" #/usr/local/etc/php/docker-php-ext-xdebug.ini alpine image
            - "./:/var/www/html"

    supervisorserver:
        image: shadow/supervisord
        volumes:
            - "./etc/supervisor-config:/etc/supervisord.d"
            - "./:/var/www/html"
        networks:
            - hello

    redisserver: 
        image: redis:alpine
        volumes:
            - "./etc/redis:/data"
        networks:
            - hello

networks:
    hello: